"use client";

import { useMemo, useRef, useState } from "react";
import { Html } from "@react-three/drei";
import { useFrame, type ThreeEvent } from "@react-three/fiber";
import type { Mesh } from "three";
import { useSceneStore } from "@/lib/sceneStore";
import type { BaseAsset } from "@/lib/schema";

/** Stable key prefix identifying a virtual (non-mesh) hotspot component. */
export const VIRTUAL_KEY_PREFIX = "__virtual_";

export function virtualComponentKey(index: number): string {
  return `${VIRTUAL_KEY_PREFIX}${index}`;
}

export function isVirtualComponentKey(key: string): boolean {
  return key.startsWith(VIRTUAL_KEY_PREFIX);
}

/** Pull the index back out of a virtual component key, or null if it isn't one. */
export function virtualComponentIndex(key: string): number | null {
  if (!isVirtualComponentKey(key)) return null;
  const n = Number(key.slice(VIRTUAL_KEY_PREFIX.length));
  return Number.isFinite(n) ? n : null;
}

/**
 * Map a component's normalized bounding-box position (-1..1 per axis, as
 * generated by lib/componentNaming.ts's getVirtualComponents) onto the
 * asset's actual WORLD-SPACE bounding box. Virtual hotspots render as
 * siblings of the scaled model group, in the same world space as
 * `asset.boundingBox` (already post scale + yOffset) — so no additional
 * transform is needed here, unlike the raw GLB scene.
 */
function normalizedToWorld(
  pos: readonly [number, number, number],
  bbox: BaseAsset["boundingBox"],
): [number, number, number] {
  const u = pos.map((n) => (n + 1) / 2);
  return [
    bbox.min[0] + u[0] * (bbox.max[0] - bbox.min[0]),
    bbox.min[1] + u[1] * (bbox.max[1] - bbox.min[1]),
    bbox.min[2] + u[2] * (bbox.max[2] - bbox.min[2]),
  ];
}

const DOT_COLOR = "#6366f1";
const DOT_HOVER_COLOR = "#818cf8";
const BASE_RADIUS = 0.09;

/** One pulsing, clickable hotspot dot + hover label. */
function Hotspot({
  assetId,
  index,
  name,
  position,
}: {
  assetId: string;
  index: number;
  name: string;
  position: [number, number, number];
}) {
  const key = virtualComponentKey(index);
  const selectedComponent = useSceneStore((s) => s.selectedComponent);
  const selectComponent = useSceneStore((s) => s.selectComponent);
  const [hovered, setHovered] = useState(false);
  const meshRef = useRef<Mesh>(null);

  const isSelected = selectedComponent?.assetId === assetId && selectedComponent.key === key;

  // Gentle continuous pulse so hotspots read as "interactive" against a static model.
  useFrame(({ clock }) => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const pulse = 1 + Math.sin(clock.elapsedTime * 2.5 + index) * 0.15;
    const s = (isSelected ? 1.4 : hovered ? 1.2 : 1) * pulse;
    mesh.scale.setScalar(s);
  });

  const handleClick = (e: ThreeEvent<MouseEvent>) => {
    e.stopPropagation();
    selectComponent({ assetId, key, label: name });
  };

  return (
    <group position={position}>
      <mesh
        ref={meshRef}
        onClick={handleClick}
        onPointerOver={(e) => {
          e.stopPropagation();
          setHovered(true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          setHovered(false);
          document.body.style.cursor = "auto";
        }}
      >
        <sphereGeometry args={[BASE_RADIUS, 16, 16]} />
        <meshStandardMaterial
          color={isSelected || hovered ? DOT_HOVER_COLOR : DOT_COLOR}
          emissive={isSelected || hovered ? DOT_HOVER_COLOR : DOT_COLOR}
          emissiveIntensity={0.8}
          transparent
          opacity={0.9}
        />
      </mesh>
      {hovered && !isSelected && (
        <Html position={[0, BASE_RADIUS * 2, 0]} style={{ pointerEvents: "none" }} center>
          <div className="-translate-y-full whitespace-nowrap rounded-md border border-lab-border bg-lab-panel/95 px-2 py-1 text-xs text-white shadow-lg">
            {name}
          </div>
        </Html>
      )}
    </group>
  );
}

/**
 * Renders every virtual component of `asset` (if any) as a clickable pulsing
 * hotspot, positioned via its normalized bbox coordinates mapped onto the
 * asset's real world-space bounding box. Used for single/few-mesh models
 * where there's no real geometry to click — see lib/componentNaming.ts's
 * getVirtualComponents and CLAUDE.md's Task 2. Renders nothing if the asset
 * has no virtual components.
 */
export default function VirtualHotspots({ asset }: { asset: BaseAsset }) {
  const components = useMemo(() => asset.virtualComponents ?? [], [asset.virtualComponents]);
  if (components.length === 0) return null;

  return (
    <>
      {components.map((c, index) => (
        <Hotspot
          key={index}
          assetId={asset.id}
          index={index}
          name={c.name}
          position={normalizedToWorld(c.position, asset.boundingBox)}
        />
      ))}
    </>
  );
}
